name: CICD

on:
  workflow_dispatch: 
    inputs:
      enviroment:
        description: This is the enviorment value where the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
        - dev
        - staging
        - prod   

jobs:

  code:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     run: echo "Code clone from GitHub"

  build:
   needs: [code]
   runs-on: ubuntu-latest
   steps:
   - name: Build Docker Container
     run: echo "Docker Container build"

  test:
   needs: [code,build]
   runs-on: ubuntu-latest
   steps:
   - name: Test the container
     run: echo "Testing the container"

  deploys:
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploying the app
      run: echo "Docker compose deployed the app"
       
 
