
#This is workflow name 
name: Hello 

#This is a trigger
on:
    push:
     branches: [main]
#These are jobs inside the workflow
jobs:

#This is the name of the job
    greet:
      #This is a GitHub runner runs each job mentioned.
      runs-on: ubuntu-latest 
    steps:
    - name: says hello to users
       run: echo 'Hello Dosto'
    - name: says hello to user
       run: echo 'Hello $user'
