---
name: Myfirstyaml

on:
  workflow_dispatch:
    #push: 
    # branches: [main]
jobs:
  greets:
    runs-on: ubuntu-latest
    steps:
      - name: prints my name
        run: echo "MY NAME IS ATHARVA"
