name: portfolio

on:
   push:
      branches: [main]

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      # gets acces to you portfolio code via pre_built actions
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup GithubPages
        uses: actions/configure-pages@v4

          #static code artifacts
      - name: upload static files
        uses: actions/upload-pages-artifacts@v4

      - name: Deploy Github pages
        uses: actions/deploy-pages@v4

         